'use strict';

angular.module('campaignTrackerApp')
  .factory('prettyUrl', function () {
    var urlRegions = [
      'easternMetropolitan',
      'easternVictoria',
      'northernMetropolitan',
      'northernVictoria',
      'southEasternMetropolitan',
      'southernMetropolitan',
      'westernMetropolitan',
      'westernVictoria'
    ];

    var dataRegions = [
      'Eastern Metropolitan',
      'Eastern Victoria',
      'Northern Metropolitan',
      'Northern Victoria',
      'South Eastern Metropolitan',
      'Southern Metropolitan',
      'Western Metropolitan',
      'Western Victoria'
    ];

    var urlToDataRegions = {
      'easternMetropolitan':      'Eastern Metropolitan',
      'easternVictoria':          'Eastern Victoria',
      'northernMetropolitan':     'Northern Metropolitan',
      'northernVictoria':         'Northern Victoria',
      'southEasternMetropolitan': 'South Eastern Metropolitan',
      'southernMetropolitan':     'Southern Metropolitan',
      'westernMetropolitan':      'Western Metropolitan',
      'westernVictoria':          'Western Victoria'
    };

    var dataToUrlRegions = {
      'Eastern Metropolitan':       'easternMetropolitan',
      'Eastern Victoria':           'easternVictoria',
      'Northern Metropolitan':      'northernMetropolitan',
      'Northern Victoria':          'northernVictoria',
      'South Eastern Metropolitan': 'southEasternMetropolitan',
      'Southern Metropolitan':      'southernMetropolitan',
      'Western Metropolitan':       'westernMetropolitan',
      'Western Victoria':           'westernVictoria'
    };

    var dataDistricts = [
      "Albert Park",
      "Altona",
      "Bass",
      "Bayswater",
      "Bellarine",
      "Benambra",
      "Bendigo East",
      "Bendigo West",
      "Bentleigh",
      "Box Hill",
      "Brighton",
      "Broadmeadows",
      "Brunswick",
      "Bulleen",
      "Bundoora",
      "Buninyong",
      "Burwood",
      "Carrum",
      "Caulfield",
      "Clarinda",
      "Cranbourne",
      "Croydon",
      "Dandenong",
      "Eildon",
      "Eltham",
      "Essendon",
      "Euroa",
      "Evelyn",
      "Ferntree Gully",
      "Footscray",
      "Forest Hill",
      "Frankston",
      "Geelong",
      "Gembrook",
      "Gippsland East",
      "Gippsland South",
      "Hastings",
      "Hawthorn",
      "Ivanhoe",
      "Kew",
      "Keysborough",
      "Kororoit",
      "Lara",
      "Lowan",
      "Macedon",
      "Malvern",
      "Melbourne",
      "Melton",
      "Mildura",
      "Mill Park",
      "Monbulk",
      "Mordialloc",
      "Mornington",
      "Morwell",
      "Mount Waverley",
      "Mulgrave",
      "Murray Plains",
      "Narracan",
      "Narre Warren North",
      "Narre Warren South",
      "Nepean",
      "Niddrie",
      "Northcote",
      "Oakleigh",
      "Ovens Valley",
      "Pascoe Vale",
      "Polwarth",
      "Prahran",
      "Preston",
      "Richmond",
      "Ringwood",
      "Ripon",
      "Rowville",
      "Sandringham",
      "Shepparton",
      "South Barwon",
      "South-West Coast",
      "St Albans",
      "Sunbury",
      "Sydenham",
      "Tarneit",
      "Thomastown",
      "Warrandyte",
      "Wendouree",
      "Werribee",
      "Williamstown",
      "Yan Yean",
      "Yuroke"
    ];

    var urlDistricts = [
      "albertPark",
      "altona",
      "bass",
      "bayswater",
      "bellarine",
      "benambra",
      "bendigoEast",
      "bendigoWest",
      "bentleigh",
      "boxHill",
      "brighton",
      "broadmeadows",
      "brunswick",
      "bulleen",
      "bundoora",
      "buninyong",
      "burwood",
      "carrum",
      "caulfield",
      "clarinda",
      "cranbourne",
      "croydon",
      "dandenong",
      "eildon",
      "eltham",
      "essendon",
      "euroa",
      "evelyn",
      "ferntreeGully",
      "footscray",
      "forestHill",
      "frankston",
      "geelong",
      "gembrook",
      "gippslandEast",
      "gippslandSouth",
      "hastings",
      "hawthorn",
      "ivanhoe",
      "kew",
      "keysborough",
      "kororoit",
      "lara",
      "lowan",
      "macedon",
      "malvern",
      "melbourne",
      "melton",
      "mildura",
      "millPark",
      "monbulk",
      "mordialloc",
      "mornington",
      "morwell",
      "mountWaverley",
      "mulgrave",
      "murrayPlains",
      "narracan",
      "narreWarrenNorth",
      "narreWarrenSouth",
      "nepean",
      "niddrie",
      "northcote",
      "oakleigh",
      "ovensValley",
      "pascoeVale",
      "polwarth",
      "prahran",
      "preston",
      "richmond",
      "ringwood",
      "ripon",
      "rowville",
      "sandringham",
      "shepparton",
      "southBarwon",
      "southWestCoast",
      "stAlbans",
      "sunbury",
      "sydenham",
      "tarneit",
      "thomastown",
      "warrandyte",
      "wendouree",
      "werribee",
      "williamstown",
      "yanYean",
      "yuroke"
    ];

    var urlToDataDistricts= {
      "albertPark":"Albert Park",
      "altona":"Altona",
      "bass":"Bass",
      "bayswater":"Bayswater",
      "bellarine":"Bellarine",
      "benambra":"Benambra",
      "bendigoEast":"Bendigo East",
      "bendigoWest":"Bendigo West",
      "bentleigh":"Bentleigh",
      "boxHill":"Box Hill",
      "brighton":"Brighton",
      "broadmeadows":"Broadmeadows",
      "brunswick":"Brunswick",
      "bulleen":"Bulleen",
      "bundoora":"Bundoora",
      "buninyong":"Buninyong",
      "burwood":"Burwood",
      "carrum":"Carrum",
      "caulfield":"Caulfield",
      "clarinda":"Clarinda",
      "cranbourne":"Cranbourne",
      "croydon":"Croydon",
      "dandenong":"Dandenong",
      "eildon":"Eildon",
      "eltham":"Eltham",
      "essendon":"Essendon",
      "euroa":"Euroa",
      "evelyn":"Evelyn",
      "ferntreeGully":"Ferntree Gully",
      "footscray":"Footscray",
      "forestHill":"Forest Hill",
      "frankston":"Frankston",
      "geelong":"Geelong",
      "gembrook":"Gembrook",
      "gippslandEast":"Gippsland East",
      "gippslandSouth":"Gippsland South",
      "hastings":"Hastings",
      "hawthorn":"Hawthorn",
      "ivanhoe":"Ivanhoe",
      "kew":"Kew",
      "keysborough":"Keysborough",
      "kororoit":"Kororoit",
      "lara":"Lara",
      "lowan":"Lowan",
      "macedon":"Macedon",
      "malvern":"Malvern",
      "melbourne":"Melbourne",
      "melton":"Melton",
      "mildura":"Mildura",
      "millPark":"Mill Park",
      "monbulk":"Monbulk",
      "mordialloc":"Mordialloc",
      "mornington":"Mornington",
      "morwell":"Morwell",
      "mountWaverley":"Mount Waverley",
      "mulgrave":"Mulgrave",
      "murrayPlains":"Murray Plains",
      "narracan":"Narracan",
      "narreWarrenNorth":"Narre Warren North",
      "narreWarrenSouth":"Narre Warren South",
      "nepean":"Nepean",
      "niddrie":"Niddrie",
      "northcote":"Northcote",
      "oakleigh":"Oakleigh",
      "ovensValley":"Ovens Valley",
      "pascoeVale":"Pascoe Vale",
      "polwarth":"Polwarth",
      "prahran":"Prahran",
      "preston":"Preston",
      "richmond":"Richmond",
      "ringwood":"Ringwood",
      "ripon":"Ripon",
      "rowville":"Rowville",
      "sandringham":"Sandringham",
      "shepparton":"Shepparton",
      "southBarwon":"South Barwon",
      "southWestCoast":"South-West Coast",
      "stAlbans":"St Albans",
      "sunbury":"Sunbury",
      "sydenham":"Sydenham",
      "tarneit":"Tarneit",
      "thomastown":"Thomastown",
      "warrandyte":"Warrandyte",
      "wendouree":"Wendouree",
      "werribee":"Werribee",
      "williamstown":"Williamstown",
      "yanYean":"Yan Yean",
      "yuroke":"Yuroke"
    };
   

    var dataToUrlDistricts = {
      "Albert Park":"albertPark",
      "Altona":"altona",
      "Bass":"bass",
      "Bayswater":"bayswater",
      "Bellarine":"bellarine",
      "Benambra":"benambra",
      "Bendigo East":"bendigoEast",
      "Bendigo West":"bendigoWest",
      "Bentleigh":"bentleigh",
      "Box Hill":"boxHill",
      "Brighton":"brighton",
      "Broadmeadows":"broadmeadows",
      "Brunswick":"brunswick",
      "Bulleen":"bulleen",
      "Bundoora":"bundoora",
      "Buninyong":"buninyong",
      "Burwood":"burwood",
      "Carrum":"carrum",
      "Caulfield":"caulfield",
      "Clarinda":"clarinda",
      "Cranbourne":"cranbourne",
      "Croydon":"croydon",
      "Dandenong":"dandenong",
      "Eildon":"eildon",
      "Eltham":"eltham",
      "Essendon":"essendon",
      "Euroa":"euroa",
      "Evelyn":"evelyn",
      "Ferntree Gully":"ferntreeGully",
      "Footscray":"footscray",
      "Forest Hill":"forestHill",
      "Frankston":"frankston",
      "Geelong":"geelong",
      "Gembrook":"gembrook",
      "Gippsland East":"gippslandEast",
      "Gippsland South":"gippslandSouth",
      "Hastings":"hastings",
      "Hawthorn":"hawthorn",
      "Ivanhoe":"ivanhoe",
      "Kew":"kew",
      "Keysborough":"keysborough",
      "Kororoit":"kororoit",
      "Lara":"lara",
      "Lowan":"lowan",
      "Macedon":"macedon",
      "Malvern":"malvern",
      "Melbourne":"melbourne",
      "Melton":"melton",
      "Mildura":"mildura",
      "Mill Park":"millPark",
      "Monbulk":"monbulk",
      "Mordialloc":"mordialloc",
      "Mornington":"mornington",
      "Morwell":"morwell",
      "Mount Waverley":"mountWaverley",
      "Mulgrave":"mulgrave",
      "Murray Plains":"murrayPlains",
      "Narracan":"narracan",
      "Narre Warren North":"narreWarrenNorth",
      "Narre Warren South":"narreWarrenSouth",
      "Nepean":"nepean",
      "Niddrie":"niddrie",
      "Northcote":"northcote",
      "Oakleigh":"oakleigh",
      "Ovens Valley":"ovensValley",
      "Pascoe Vale":"pascoeVale",
      "Polwarth":"polwarth",
      "Prahran":"prahran",
      "Preston":"preston",
      "Richmond":"richmond",
      "Ringwood":"ringwood",
      "Ripon":"ripon",
      "Rowville":"rowville",
      "Sandringham":"sandringham",
      "Shepparton":"shepparton",
      "South Barwon":"southBarwon",
      "South-West Coast":"southWestCoast",
      "St Albans":"stAlbans",
      "Sunbury":"sunbury",
      "Sydenham":"sydenham",
      "Tarneit":"tarneit",
      "Thomastown":"thomastown",
      "Warrandyte":"warrandyte",
      "Wendouree":"wendouree",
      "Werribee":"werribee",
      "Williamstown":"williamstown",
      "Yan Yean":"yanYean",
      "Yuroke":"yuroke"
    };


    var urlPeople = [
      'eMPerson1',
      'eMPerson2',
      'eMPerson3',
      'eMPerson4',
      'eVPerson1',
      'eVPerson2',
      'eVPerson3',
      'eVPerson4',
      'nMPerson1',
      'nMPerson2',
      'nMPerson3',
      'mNPerson4',
      'nVPerson1',
      'nVPerson2',
      'nVPerson3',
      'nVPerson4',
      'sEMPerson1',
      'sEMPerson2',
      'sEMPerson3',
      'sEMPerson4',
      'sMPerson1',
      'sMPerson2',
      'sMPerson3',
      'sMPerson4',
      'wMPerson1',
      'wMPerson2',
      'wMPerson3',
      'wMPerson4',
      'lloydDavies',
      'maxwellSmith',
      'lauraRobertson',
      'andreTrosky',
      'billFromTorquay',
      'glenn',
      'claraDavies',
      'judyCameron'
    ];

    var dataPeople = [
      'EMPerson1',
      'EMPerson2',
      'EMPerson3',
      'EMPerson4',
      'EVPerson1',
      'EVPerson2',
      'EVPerson3',
      'EVPerson4',
      'NMPerson1',
      'NMPerson2',
      'NMPerson3',
      'MNPerson4',
      'NVPerson1',
      'NVPerson2',
      'NVPerson3',
      'NVPerson4',
      'SEMPerson1',
      'SEMPerson2',
      'SEMPerson3',
      'SEMPerson4',
      'SMPerson1',
      'SMPerson2',
      'SMPerson3',
      'SMPerson4',
      'WMPerson1',
      'WMPerson2',
      'WMPerson3',
      'WMPerson4',
      'Lloyd Davies',
      'Maxwell Smith',
      'Laura Robertson',
      'Andre Trosky',
      'Bill From Torquay',
      'Glenn',
      'Clara Davies',
      'Judy Cameron'
    ];

    var urlToDataPeople = {
      'eMPerson1':'EMPerson1',
      'eMPerson2':'EMPerson2',
      'eMPerson3':'EMPerson3',
      'eMPerson4':'EMPerson4',
      'eVPerson1':'EVPerson1',
      'eVPerson2':'EVPerson2',
      'eVPerson3':'EVPerson3',
      'eVPerson4':'EVPerson4',
      'nMPerson1':'NMPerson1',
      'nMPerson2':'NMPerson2',
      'nMPerson3':'NMPerson3',
      'mNPerson4':'MNPerson4',
      'nVPerson1':'NVPerson1',
      'nVPerson2':'NVPerson2',
      'nVPerson3':'NVPerson3',
      'nVPerson4':'NVPerson4',
      'sEMPerson1':'SEMPerson1',
      'sEMPerson2':'SEMPerson2',
      'sEMPerson3':'SEMPerson3',
      'sEMPerson4':'SEMPerson4',
      'sMPerson1':'SMPerson1',
      'sMPerson2':'SMPerson2',
      'sMPerson3':'SMPerson3',
      'sMPerson4':'SMPerson4',
      'wMPerson1':'WMPerson1',
      'wMPerson2':'WMPerson2',
      'wMPerson3':'WMPerson3',
      'wMPerson4':'WMPerson4',
      'lloydDavies':'Lloyd Davies',
      'maxwellSmith':'Maxwell Smith',
      'lauraRobertson':'Laura Robertson',
      'andreTrosky':'Andre Trosky',
      'billFromTorquay':'Bill From Torquay',
      'glenn':'Glenn',
      'claraDavies':'Clara Davies',
      'judyCameron':'Judy Cameron'
    };

    var dataToUrlPeople = {
      'EMPerson1':'eMPerson1',
      'EMPerson2':'eMPerson2',
      'EMPerson3':'eMPerson3',
      'EMPerson4':'eMPerson4',
      'EVPerson1':'eVPerson1',
      'EVPerson2':'eVPerson2',
      'EVPerson3':'eVPerson3',
      'EVPerson4':'eVPerson4',
      'NMPerson1':'nMPerson1',
      'NMPerson2':'nMPerson2',
      'NMPerson3':'nMPerson3',
      'MNPerson4':'mNPerson4',
      'NVPerson1':'nVPerson1',
      'NVPerson2':'nVPerson2',
      'NVPerson3':'nVPerson3',
      'NVPerson4':'nVPerson4',
      'SEMPerson1':'sEMPerson1',
      'SEMPerson2':'sEMPerson2',
      'SEMPerson3':'sEMPerson3',
      'SEMPerson4':'sEMPerson4',
      'SMPerson1':'sMPerson1',
      'SMPerson2':'sMPerson2',
      'SMPerson3':'sMPerson3',
      'SMPerson4':'sMPerson4',
      'WMPerson1':'wMPerson1',
      'WMPerson2':'wMPerson2',
      'WMPerson3':'wMPerson3',
      'WMPerson4':'wMPerson4',
      'Lloyd Davies':'lloydDavies',
      'Maxwell Smith':'maxwellSmith',
      'Laura Robertson':'lauraRobertson',
      'Andre Trosky':'andreTrosky',
      'Bill From Torquay':'billFromTorquay',
      'Glenn':'glenn',
      'Clara Davies':'claraDavies',
      'Judy Cameron':'judyCameron'
    };

    var urlNTeams = [
      'eMTeam1',
      'eMTeam2',
      'eMTeam3',
      'eMTeam4',
      'eVTeam1',
      'eVTeam2',
      'eVTeam3',
      'eVTeam4',
      'nMTeam1',
      'nMTeam2',
      'nMTeam3',
      'mNTeam4',
      'nVTeam1',
      'nVTeam2',
      'nVTeam3',
      'nVTeam4',
      'sEMTeam1',
      'sEMTeam2',
      'sEMTeam3',
      'sEMTeam4',
      'sMTeam1',
      'sMTeam2',
      'sMTeam3',
      'sMTeam4',
      'wMTeam1',
      'wMTeam2',
      'wMTeam3',
      'wMTeam4',
      'ocean Grove',
      'torquay',
      'geelong',
      'lara',
      'werribee',
      'apolloBay'
    ];
   
    var dataNTeams = [
      'EMTeam1',
      'EMTeam2',
      'EMTeam3',
      'EMTeam4',
      'EVTeam1',
      'EVTeam2',
      'EVTeam3',
      'EVTeam4',
      'NMTeam1',
      'NMTeam2',
      'NMTeam3',
      'MNTeam4',
      'NVTeam1',
      'NVTeam2',
      'NVTeam3',
      'NVTeam4',
      'SEMTeam1',
      'SEMTeam2',
      'SEMTeam3',
      'SEMTeam4',
      'SMTeam1',
      'SMTeam2',
      'SMTeam3',
      'SMTeam4',
      'WMTeam1',
      'WMTeam2',
      'WMTeam3',
      'WMTeam4',
      'Ocean Grove',
      'Torquay',
      'Geelong',
      'Lara',
      'Werribee',
      'Apollo Bay'

    ];

    var urlToDataNTeams = {
      'eMTeam1':'EMTeam1',
      'eMTeam2':'EMTeam2',
      'eMTeam3':'EMTeam3',
      'eMTeam4':'EMTeam4',
      'eVTeam1':'EVTeam1',
      'eVTeam2':'EVTeam2',
      'eVTeam3':'EVTeam3',
      'eVTeam4':'EVTeam4',
      'nMTeam1':'NMTeam1',
      'nMTeam2':'NMTeam2',
      'nMTeam3':'NMTeam3',
      'mNTeam4':'MNTeam4',
      'nVTeam1':'NVTeam1',
      'nVTeam2':'NVTeam2',
      'nVTeam3':'NVTeam3',
      'nVTeam4':'NVTeam4',
      'sEMTeam1':'SEMTeam1',
      'sEMTeam2':'SEMTeam2',
      'sEMTeam3':'SEMTeam3',
      'sEMTeam4':'SEMTeam4',
      'sMTeam1':'SMTeam1',
      'sMTeam2':'SMTeam2',
      'sMTeam3':'SMTeam3',
      'sMTeam4':'SMTeam4',
      'wMTeam1':'WMTeam1',
      'wMTeam2':'WMTeam2',
      'wMTeam3':'WMTeam3',
      'wMTeam4':'WMTeam4',
      'oceanGrove':'Ocean Grove',
      'torquay':'Torquay',
      'geelong':'Geelong',
      'lara':'Lara',
      'werribee':'Werribee',
      'apolloBay':'Apollo Bay'
    };

    var dataToUrlNTeams = {
      'EMTeam1':'eMTeam1',
      'EMTeam2':'eMTeam2',
      'EMTeam3':'eMTeam3',
      'EMTeam4':'eMTeam4',
      'EVTeam1':'eVTeam1',
      'EVTeam2':'eVTeam2',
      'EVTeam3':'eVTeam3',
      'EVTeam4':'eVTeam4',
      'NMTeam1':'nMTeam1',
      'NMTeam2':'nMTeam2',
      'NMTeam3':'nMTeam3',
      'MNTeam4':'mNTeam4',
      'NVTeam1':'nVTeam1',
      'NVTeam2':'nVTeam2',
      'NVTeam3':'nVTeam3',
      'NVTeam4':'nVTeam4',
      'SEMTeam1':'sEMTeam1',
      'SEMTeam2':'sEMTeam2',
      'SEMTeam3':'sEMTeam3',
      'SEMTeam4':'sEMTeam4',
      'SMTeam1':'sMTeam1',
      'SMTeam2':'sMTeam2',
      'SMTeam3':'sMTeam3',
      'SMTeam4':'sMTeam4',
      'WMTeam1':'wMTeam1',
      'WMTeam2':'wMTeam2',
      'WMTeam3':'wMTeam3',
      'WMTeam4':'wMTeam4',
      'Ocean Grove':'oceanGrove',
      'Torquay':'torquay',
      'Geelong':'geelong',
      'Lara':'lara',
      'Werribee':'werribee',
      'Apollo Bay':'apolloBay'
    };

    return {
      urlRegions:         urlRegions,
      dataRegions:        dataRegions,
      urlToDataRegions:   urlToDataRegions,
      dataToUrlRegions:   dataToUrlRegions,
      urlDistricts:       urlDistricts,
      dataDistricts:      dataDistricts,
      urlToDataDistricts: urlToDataDistricts,
      dataToUrlDistricts: dataToUrlDistricts,
      urlPeople:          urlPeople,
      dataPeople:         dataPeople,
      urlToDataPeople:    urlToDataPeople,
      dataToUrlPeople:    dataToUrlPeople,
      urlNTeams:          urlNTeams,
      dataNTeams:         dataNTeams,
      urlToDataNTeams:    urlToDataNTeams,
      dataToUrlNTeams:    dataToUrlNTeams
    };
});
