'use strict';

angular.module('campaignTrackerApp')
  .factory('prettyUrl', function () {
    var urlRegions = [
      'easternMetropolitan',
      'easternVictoria',
      'northernMetropolitan',
      'northernVictoria',
      'southEasternMetropolitan',
      'southernMetropolitan',
      'westernMetropolitan',
      'westernVictoria'
    ];

    var dataRegions = [
      'Eastern Metropolitan',
      'Eastern Victoria',
      'Northern Metropolitan',
      'Northern Victoria',
      'South Eastern Metropolitan',
      'Southern Metropolitan',
      'Western Metropolitan',
      'Western Victoria'
    ];

    var urlToDataRegions = {
      'easternMetropolitan':      'Eastern Metropolitan',
      'easternVictoria':          'Eastern Victoria',
      'northernMetropolitan':     'Northern Metropolitan',
      'northernVictoria':         'Northern Victoria',
      'southEasternMetropolitan': 'South Eastern Metropolitan',
      'southernMetropolitan':     'Southern Metropolitan',
      'westernMetropolitan':      'Western Metropolitan',
      'westernVictoria':          'Western Victoria'
    };

    var dataToUrlRegions = {
      'Eastern Metropolitan':       'easternMetropolitan',
      'Eastern Victoria':           'easternVictoria',
      'Northern Metropolitan':      'northernMetropolitan',
      'Northern Victoria':          'northernVictoria',
      'South Eastern Metropolitan': 'southEasternMetropolitan',
      'Southern Metropolitan':      'southernMetropolitan',
      'Western Metropolitan':       'westernMetropolitan',
      'Western Victoria':           'westernVictoria'
    };

    var urlDistricts = [
      "bayswater",
      "boxHill",
      "bulleen",
      "doncaster",
      "eltham",
      "ferntreeGully",
      "forestHill",
      "kilsyth",
      "mitcham",
      "scoresby",
      "warrandyte",
      "bass",
      "evelyn",
      "gembrook",
      "gippslandEast",
      "gippslandSouth",
      "hastings",
      "monbulk",
      "mornington",
      "morwell",
      "narracan",
      "nepean",
      "broadmeadows",
      "brunswick",
      "bundoora",
      "ivanhoe",
      "melbourne",
      "millPark",
      "northcote",
      "preston",
      "richmond",
      "thomastown",
      "yanYean",
      "benalla",
      "benambra",
      "bendigoEast",
      "bendigoWest",
      "macedon",
      "mildura",
      "murrayValley",
      "rodney",
      "seymour",
      "shepparton",
      "swanHill",
      "carrum",
      "clayton",
      "cranbourne",
      "dandenong",
      "frankston",
      "lyndhurst",
      "mordialloc",
      "mountWaverley",
      "mulgrave",
      "narreWarrenNorth",
      "narreWarrenSouth",
      "albertPark",
      "bentleigh",
      "brighton",
      "burwood",
      "caulfield",
      "hawthorn",
      "kew",
      "malvern",
      "oakleigh",
      "prahran",
      "sandringham",
      "altona",
      "derrimut",
      "essendon",
      "footscray",
      "keilor",
      "kororoit",
      "niddrie",
      "pascoeVale",
      "tarneit",
      "williamstown",
      "yuroke",
      "ballaratEast",
      "ballaratWest",
      "bellarine",
      "geelong",
      "lara",
      "lowan",
      "melton",
      "polwarth",
      "ripon",
      "southBarwon",
      "southWestCoast"
    ];
    var dataDistricts = [
      "Bayswater",
      "Box Hill",
      "Bulleen",
      "Doncaster",
      "Eltham",
      "Ferntree Gully",
      "Forest Hill",
      "Kilsyth",
      "Mitcham",
      "Scoresby",
      "Warrandyte",
      "Bass",
      "Evelyn",
      "Gembrook",
      "Gippsland East",
      "Gippsland South",
      "Hastings",
      "Monbulk",
      "Mornington",
      "Morwell",
      "Narracan",
      "Nepean",
      "Broadmeadows",
      "Brunswick",
      "Bundoora",
      "Ivanhoe",
      "Melbourne",
      "Mill Park",
      "Northcote",
      "Preston",
      "Richmond",
      "Thomastown",
      "Yan Yean",
      "Benalla",
      "Benambra",
      "Bendigo East",
      "Bendigo West",
      "Macedon",
      "Mildura",
      "Murray Valley",
      "Rodney",
      "Seymour",
      "Shepparton",
      "Swan Hill",
      "Carrum",
      "Clayton",
      "Cranbourne",
      "Dandenong",
      "Frankston",
      "Lyndhurst",
      "Mordialloc",
      "Mount Waverley",
      "Mulgrave",
      "Narre Warren North",
      "Narre Warren South",
      "Albert Park",
      "Bentleigh",
      "Brighton",
      "Burwood",
      "Caulfield",
      "Hawthorn",
      "Kew",
      "Malvern",
      "Oakleigh",
      "Prahran",
      "Sandringham",
      "Altona",
      "Derrimut",
      "Essendon",
      "Footscray",
      "Keilor",
      "Kororoit",
      "Niddrie",
      "Pascoe Vale",
      "Tarneit",
      "Williamstown",
      "Yuroke",
      "Ballarat East",
      "Ballarat West",
      "Bellarine",
      "Geelong",
      "Lara",
      "Lowan",
      "Melton",
      "Polwarth",
      "Ripon",
      "South Barwon",
      "South-West Coast"
    ];


    var urlToDataDistricts= {
      "bayswater":"Bayswater",
      "boxHill":"Box Hill",
      "bulleen":"Bulleen",
      "doncaster":"Doncaster",
      "eltham":"Eltham",
      "ferntreeGully":"Ferntree Gully",
      "forestHill":"Forest Hill",
      "kilsyth":"Kilsyth",
      "mitcham":"Mitcham",
      "scoresby":"Scoresby",
      "warrandyte":"Warrandyte",
      "bass":"Bass",
      "evelyn":"Evelyn",
      "gembrook":"Gembrook",
      "gippslandEast":"Gippsland East",
      "gippslandSouth":"Gippsland South",
      "hastings":"Hastings",
      "monbulk":"Monbulk",
      "mornington":"Mornington",
      "morwell":"Morwell",
      "narracan":"Narracan",
      "nepean":"Nepean",
      "broadmeadows":"Broadmeadows",
      "brunswick":"Brunswick",
      "bundoora":"Bundoora",
      "ivanhoe":"Ivanhoe",
      "melbourne":"Melbourne",
      "millPark":"MillPark",
      "northcote":"Northcote",
      "preston":"Preston",
      "richmond":"Richmond",
      "thomastown":"Thomastown",
      "yanYean":"Yan Yean",
      "benalla":"Benalla",
      "benambra":"Benambra",
      "bendigoEast":"Bendigo East",
      "bendigoWest":"Bendigo West",
      "macedon":"Macedon",
      "mildura":"Mildura",
      "murrayValley":"Murray Valley",
      "rodney":"Rodney",
      "seymour":"Seymour",
      "shepparton":"Shepparton",
      "swanHill":"Swan Hill",
      "carrum":"Carrum",
      "clayton":"Clayton",
      "cranbourne":"Cranbourne",
      "dandenong":"Dandenong",
      "frankston":"Frankston",
      "lyndhurst":"Lyndhurst",
      "mordialloc":"Mordialloc",
      "mountWaverley":"Mount Waverley",
      "mulgrave":"Mulgrave",
      "narreWarrenNorth":"Narre Warren North",
      "narreWarrenSouth":"Narre Warren South",
      "albertPark":"Albert Park",
      "bentleigh":"Bentleigh",
      "brighton":"Brighton",
      "burwood":"Burwood",
      "caulfield":"Caulfield",
      "hawthorn":"Hawthorn",
      "kew":"Kew",
      "malvern":"Malvern",
      "oakleigh":"Oakleigh",
      "prahran":"Prahran",
      "sandringham":"Sandringham",
      "altona":"Altona",
      "derrimut":"Derrimut",
      "essendon":"Essendon",
      "footscray":"Footscray",
      "keilor":"Keilor",
      "kororoit":"Kororoit",
      "niddrie":"Niddrie",
      "pascoeVale":"Pascoe Vale",
      "tarneit":"Tarneit",
      "williamstown":"Williamstown",
      "yuroke":"Yuroke",
      "ballaratEast":"Ballarat East",
      "ballaratWest":"Ballarat West",
      "bellarine":"Bellarine",
      "geelong":"Geelong",
      "lara":"Lara",
      "lowan":"Lowan",
      "melton":"Melton",
      "polwarth":"Polwarth",
      "ripon":"Ripon",
      "southBarwon":"South Barwon",
      "southWestCoast":"South-West Coast"
    };

    var dataToUrlDistricts = {
      "Bayswater":"bayswater",
      "Box Hill":"boxHill",
      "Bulleen":"bulleen",
      "Doncaster":"doncaster",
      "Eltham":"eltham",
      "Ferntree Gully":"ferntreeGully",
      "Forest Hill":"forestHill",
      "Kilsyth":"kilsyth",
      "Mitcham":"mitcham",
      "Scoresby":"scoresby",
      "Warrandyte":"warrandyte",
      "Bass":"bass",
      "Evelyn":"evelyn",
      "Gembrook":"gembrook",
      "Gippsland East":"gippslandEast",
      "Gippsland South":"gippslandSouth",
      "Hastings":"hastings",
      "Monbulk":"monbulk",
      "Mornington":"mornington",
      "Morwell":"morwell",
      "Narracan":"narracan",
      "Nepean":"nepean",
      "Broadmeadows":"broadmeadows",
      "Brunswick":"brunswick",
      "Bundoora":"bundoora",
      "Ivanhoe":"ivanhoe",
      "Melbourne":"melbourne",
      "Mill Park":"millPark",
      "Northcote":"northcote",
      "Preston":"preston",
      "Richmond":"richmond",
      "Thomastown":"thomastown",
      "Yan Yean":"yanYean",
      "Benalla":"benalla",
      "Benambra":"benambra",
      "Bendigo East":"bendigoEast",
      "Bendigo West":"bendigoWest",
      "Macedon":"macedon",
      "Mildura":"mildura",
      "Murray Valley":"murrayValley",
      "Rodney":"rodney",
      "Seymour":"seymour",
      "Shepparton":"shepparton",
      "Swan Hill":"swan Hill",
      "Carrum":"carrum",
      "Clayton":"clayton",
      "Cranbourne":"cranbourne",
      "Dandenong":"dandenong",
      "Frankston":"frankston",
      "Lyndhurst":"lyndhurst",
      "Mordialloc":"mordialloc",
      "Mount Waverley":"mountWaverley",
      "Mulgrave":"mulgrave",
      "Narre Warren North":"narreWarrenNorth",
      "Narre Warren South":"narreWarrenSouth",
      "Albert Park":"albertPark",
      "Bentleigh":"bentleigh",
      "Brighton":"brighton",
      "Burwood":"burwood",
      "Caulfield":"caulfield",
      "Hawthorn":"hawthorn",
      "Kew":"kew",
      "Malvern":"malvern",
      "Oakleigh":"oakleigh",
      "Prahran":"prahran",
      "Sandringham":"sandringham",
      "Altona":"altona",
      "Derrimut":"derrimut",
      "Essendon":"essendon",
      "Footscray":"footscray",
      "Keilor":"keilor",
      "Kororoit":"kororoit",
      "Niddrie":"niddrie",
      "Pascoe Vale":"pascoeVale",
      "Tarneit":"tarneit",
      "Williamstown":"williamstown",
      "Yuroke":"yuroke",
      "Ballarat East":"ballaratEast",
      "Ballarat West":"ballaratWest",
      "Bellarine":"bellarine",
      "Geelong":"geelong",
      "Lara":"lara",
      "Lowan":"lowan",
      "Melton":"melton",
      "Polwarth":"polwarth",
      "Ripon":"ripon",
      "South Barwon":"southBarwon",
      "South-West Coast":"southWestCoast"
    };


    var urlPeople = [
      'eMPerson1',
      'eMPerson2',
      'eMPerson3',
      'eMPerson4',
      'eVPerson1',
      'eVPerson2',
      'eVPerson3',
      'eVPerson4',
      'nMPerson1',
      'nMPerson2',
      'nMPerson3',
      'mNPerson4',
      'nVPerson1',
      'nVPerson2',
      'nVPerson3',
      'nVPerson4',
      'sEMPerson1',
      'sEMPerson2',
      'sEMPerson3',
      'sEMPerson4',
      'sMPerson1',
      'sMPerson2',
      'sMPerson3',
      'sMPerson4',
      'wMPerson1',
      'wMPerson2',
      'wMPerson3',
      'wMPerson4',
      'lloydDavies',
      'maxwellSmith',
      'lauraRobertson',
      'andreTrosky',
      'billFromTorquay',
      'glenn',
      'claraDavies',
      'judyCameron'
    ];

    var dataPeople = [
      'EMPerson1',
      'EMPerson2',
      'EMPerson3',
      'EMPerson4',
      'EVPerson1',
      'EVPerson2',
      'EVPerson3',
      'EVPerson4',
      'NMPerson1',
      'NMPerson2',
      'NMPerson3',
      'MNPerson4',
      'NVPerson1',
      'NVPerson2',
      'NVPerson3',
      'NVPerson4',
      'SEMPerson1',
      'SEMPerson2',
      'SEMPerson3',
      'SEMPerson4',
      'SMPerson1',
      'SMPerson2',
      'SMPerson3',
      'SMPerson4',
      'WMPerson1',
      'WMPerson2',
      'WMPerson3',
      'WMPerson4',
      'Lloyd Davies',
      'Maxwell Smith',
      'Laura Robertson',
      'Andre Trosky',
      'Bill From Torquay',
      'Glenn',
      'Clara Davies',
      'Judy Cameron'
    ];

    var urlToDataPeople = {
      'eMPerson1':'EMPerson1',
      'eMPerson2':'EMPerson2',
      'eMPerson3':'EMPerson3',
      'eMPerson4':'EMPerson4',
      'eVPerson1':'EVPerson1',
      'eVPerson2':'EVPerson2',
      'eVPerson3':'EVPerson3',
      'eVPerson4':'EVPerson4',
      'nMPerson1':'NMPerson1',
      'nMPerson2':'NMPerson2',
      'nMPerson3':'NMPerson3',
      'mNPerson4':'MNPerson4',
      'nVPerson1':'NVPerson1',
      'nVPerson2':'NVPerson2',
      'nVPerson3':'NVPerson3',
      'nVPerson4':'NVPerson4',
      'sEMPerson1':'SEMPerson1',
      'sEMPerson2':'SEMPerson2',
      'sEMPerson3':'SEMPerson3',
      'sEMPerson4':'SEMPerson4',
      'sMPerson1':'SMPerson1',
      'sMPerson2':'SMPerson2',
      'sMPerson3':'SMPerson3',
      'sMPerson4':'SMPerson4',
      'wMPerson1':'WMPerson1',
      'wMPerson2':'WMPerson2',
      'wMPerson3':'WMPerson3',
      'wMPerson4':'WMPerson4',
      'lloydDavies':'Lloyd Davies',
      'maxwellSmith':'Maxwell Smith',
      'lauraRobertson':'Laura Robertson',
      'andreTrosky':'Andre Trosky',
      'billFromTorquay':'Bill From Torquay',
      'glenn':'Glenn',
      'claraDavies':'Clara Davies',
      'judyCameron':'Judy Cameron'
    };

    var dataToUrlPeople = {
      'EMPerson1':'eMPerson1',
      'EMPerson2':'eMPerson2',
      'EMPerson3':'eMPerson3',
      'EMPerson4':'eMPerson4',
      'EVPerson1':'eVPerson1',
      'EVPerson2':'eVPerson2',
      'EVPerson3':'eVPerson3',
      'EVPerson4':'eVPerson4',
      'NMPerson1':'nMPerson1',
      'NMPerson2':'nMPerson2',
      'NMPerson3':'nMPerson3',
      'MNPerson4':'mNPerson4',
      'NVPerson1':'nVPerson1',
      'NVPerson2':'nVPerson2',
      'NVPerson3':'nVPerson3',
      'NVPerson4':'nVPerson4',
      'SEMPerson1':'sEMPerson1',
      'SEMPerson2':'sEMPerson2',
      'SEMPerson3':'sEMPerson3',
      'SEMPerson4':'sEMPerson4',
      'SMPerson1':'sMPerson1',
      'SMPerson2':'sMPerson2',
      'SMPerson3':'sMPerson3',
      'SMPerson4':'sMPerson4',
      'WMPerson1':'wMPerson1',
      'WMPerson2':'wMPerson2',
      'WMPerson3':'wMPerson3',
      'WMPerson4':'wMPerson4',
      'Lloyd Davies':'lloydDavies',
      'Maxwell Smith':'maxwellSmith',
      'Laura Robertson':'lauraRobertson',
      'Andre Trosky':'andreTrosky',
      'Bill From Torquay':'billFromTorquay',
      'Glenn':'glenn',
      'Clara Davies':'claraDavies',
      'Judy Cameron':'judyCameron'
    };

    var urlNTeams = [
      'eMTeam1',
      'eMTeam2',
      'eMTeam3',
      'eMTeam4',
      'eVTeam1',
      'eVTeam2',
      'eVTeam3',
      'eVTeam4',
      'nMTeam1',
      'nMTeam2',
      'nMTeam3',
      'mNTeam4',
      'nVTeam1',
      'nVTeam2',
      'nVTeam3',
      'nVTeam4',
      'sEMTeam1',
      'sEMTeam2',
      'sEMTeam3',
      'sEMTeam4',
      'sMTeam1',
      'sMTeam2',
      'sMTeam3',
      'sMTeam4',
      'wMTeam1',
      'wMTeam2',
      'wMTeam3',
      'wMTeam4',
      'ocean Grove',
      'torquay',
      'geelong',
      'lara',
      'werribee',
      'apolloBay'
    ];
   
    var dataNTeams = [
      'EMTeam1',
      'EMTeam2',
      'EMTeam3',
      'EMTeam4',
      'EVTeam1',
      'EVTeam2',
      'EVTeam3',
      'EVTeam4',
      'NMTeam1',
      'NMTeam2',
      'NMTeam3',
      'MNTeam4',
      'NVTeam1',
      'NVTeam2',
      'NVTeam3',
      'NVTeam4',
      'SEMTeam1',
      'SEMTeam2',
      'SEMTeam3',
      'SEMTeam4',
      'SMTeam1',
      'SMTeam2',
      'SMTeam3',
      'SMTeam4',
      'WMTeam1',
      'WMTeam2',
      'WMTeam3',
      'WMTeam4',
      'Ocean Grove',
      'Torquay',
      'Geelong',
      'Lara',
      'Werribee',
      'Apollo Bay'

    ];

    var urlToDataNTeams = {
      'eMTeam1':'EMTeam1',
      'eMTeam2':'EMTeam2',
      'eMTeam3':'EMTeam3',
      'eMTeam4':'EMTeam4',
      'eVTeam1':'EVTeam1',
      'eVTeam2':'EVTeam2',
      'eVTeam3':'EVTeam3',
      'eVTeam4':'EVTeam4',
      'nMTeam1':'NMTeam1',
      'nMTeam2':'NMTeam2',
      'nMTeam3':'NMTeam3',
      'mNTeam4':'MNTeam4',
      'nVTeam1':'NVTeam1',
      'nVTeam2':'NVTeam2',
      'nVTeam3':'NVTeam3',
      'nVTeam4':'NVTeam4',
      'sEMTeam1':'SEMTeam1',
      'sEMTeam2':'SEMTeam2',
      'sEMTeam3':'SEMTeam3',
      'sEMTeam4':'SEMTeam4',
      'sMTeam1':'SMTeam1',
      'sMTeam2':'SMTeam2',
      'sMTeam3':'SMTeam3',
      'sMTeam4':'SMTeam4',
      'wMTeam1':'WMTeam1',
      'wMTeam2':'WMTeam2',
      'wMTeam3':'WMTeam3',
      'wMTeam4':'WMTeam4',
      'oceanGrove':'Ocean Grove',
      'torquay':'Torquay',
      'geelong':'Geelong',
      'lara':'Lara',
      'werribee':'Werribee',
      'apolloBay':'Apollo Bay'
    };

    var dataToUrlNTeams = {
      'EMTeam1':'eMTeam1',
      'EMTeam2':'eMTeam2',
      'EMTeam3':'eMTeam3',
      'EMTeam4':'eMTeam4',
      'EVTeam1':'eVTeam1',
      'EVTeam2':'eVTeam2',
      'EVTeam3':'eVTeam3',
      'EVTeam4':'eVTeam4',
      'NMTeam1':'nMTeam1',
      'NMTeam2':'nMTeam2',
      'NMTeam3':'nMTeam3',
      'MNTeam4':'mNTeam4',
      'NVTeam1':'nVTeam1',
      'NVTeam2':'nVTeam2',
      'NVTeam3':'nVTeam3',
      'NVTeam4':'nVTeam4',
      'SEMTeam1':'sEMTeam1',
      'SEMTeam2':'sEMTeam2',
      'SEMTeam3':'sEMTeam3',
      'SEMTeam4':'sEMTeam4',
      'SMTeam1':'sMTeam1',
      'SMTeam2':'sMTeam2',
      'SMTeam3':'sMTeam3',
      'SMTeam4':'sMTeam4',
      'WMTeam1':'wMTeam1',
      'WMTeam2':'wMTeam2',
      'WMTeam3':'wMTeam3',
      'WMTeam4':'wMTeam4',
      'Ocean Grove':'oceanGrove',
      'Torquay':'torquay',
      'Geelong':'geelong',
      'Lara':'lara',
      'Werribee':'werribee',
      'Apollo Bay':'apolloBay'
    };

    return {
      urlRegions:         urlRegions,
      dataRegions:        dataRegions,
      urlToDataRegions:   urlToDataRegions,
      dataToUrlRegions:   dataToUrlRegions,
      urlDistricts:       urlDistricts,
      dataDistricts:      dataDistricts,
      urlToDataDistricts: urlToDataDistricts,
      dataToUrlDistricts: dataToUrlDistricts,
      urlPeople:          urlPeople,
      dataPeople:         dataPeople,
      urlToDataPeople:    urlToDataPeople,
      dataToUrlPeople:    dataToUrlPeople,
      urlNTeams:          urlNTeams,
      dataNTeams:         dataNTeams,
      urlToDataNTeams:     urlToDataNTeams,
      dataToUrlNTeams:     dataToUrlNTeams
    };
});
